### PR TITLE
fix(accordion, accordion-item): `icon-position`, `icon-type`, `selection-mode` and `scale` can now be set as props or attributes

### LINKED ISSUE #6199: Accordion icon-position can only be set as an attribute
### Actual Behavior

If you set `accordionEl.iconPosition = "start"` the icons of the children accordion items will still appear at the end of the accordion. 

However, if you use `accordionEl.setAttribute("icon-position", "start")` or just set it with kebab case in the DOM, it works great. 

### Expected Behavior

All props should function using either attributes or... props. We generally prefer using the camel case versions as you get much better type hinting for the values. 

### Reproduction Sample

https://codepen.io/paulcp/pen/VwBaPEd?editors=0010

### Reproduction Steps

1. look at the icon position (will be at the end)
2. now change the code to use the attribute version
3. notice the icon moves to the start

### Reproduction Version

All

### Relevant Info

_No response_

### Regression?

_No response_

### Impact

_No response_

### Esri team

ArcGIS Online

### PR DESCRIPTION
**Pull request by Elijbet**
**Related Issue:** #6199, #6038, #6200

## Summary

This should resolve #6199, where you're able to set `accordionEl.setAttribute("icon-position", "start")`, but not  `accordionEl.iconPosition = "start"`, happening because of a logical issue within `getElementProp` function.

`getElementProp` is being refactored across child components as an outdated pattern in #6038, so this will also kick off that issue as well.

Instead of the `accordion-item` looking up the parent for `iconPosition, iconType, selectionMode, or scale`, these get set by the `accordion` parent. 

The logic for setting these props thus moves to the parent, getting rid of the `getElementProp` altogether. The parent component gets a `mutation observer` to do this as well as `watchers` for when it needs to modify the children.

With the `mutationObserver` added, there is no longer a need for the `calciteInternalAccordionItemRegister` event logic.

### CODE REVIEW

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 1]
```diff
@@ -116,6 +145,9 @@ export class Accordion {
   //  Private State/Props
   //
   //--------------------------------------------------------------------------
+  mutationObserver = createObserver("mutation", () => this.passPropsToAccordionItems());
+
+  @State() accordionItems: HTMLCalciteAccordionItemElement[] = [];
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion/accordion.tsx:150]: I don't think this needs to be state since its not rendering.

File: packages/calcite-components/src/components/accordion-item/accordion-item.tsx [hunk 2]
```diff
@@ -69,6 +68,37 @@ export class AccordionItem implements ConditionalSlotComponent {
...
+   *
+   * @internal
+   */
+  @Prop({ reflect: false, mutable: false }) iconPosition: Position = "end";
+
+  /** Specifies the type of the icon in the header inherited from the `calcite-accordion`.
+   *
+   * @internal
+   */
+  @Prop({ reflect: false, mutable: false }) iconType: "chevron" | "caret" | "plus-minus" =
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion-item/accordion-item.tsx:82]: `mutable: false` is default so this can be removed.

File: packages/calcite-components/src/components/accordion-item/accordion-item.tsx [hunk 3]
```diff
@@ -98,10 +128,6 @@ export class AccordionItem implements ConditionalSlotComponent {
 
   connectedCallback(): void {
     this.parent = this.el.parentElement as HTMLCalciteAccordionElement;
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion-item/accordion-item.tsx:130]: The parent could probably be set as well.

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 4]
```diff
@@ -45,6 +57,14 @@ export class Accordion {
     SelectionMode
   > = "multiple";
 
+  @Watch("iconPosition")
+  @Watch("iconType")
+  @Watch("scale")
+  @Watch("selectionMode")
+  onInternalPropChange(): void {
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion/accordion.tsx:64]: maybe `handlePropsChange`? Since these aren't internal at this point.

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 5]
```diff
@@ -62,13 +82,22 @@ export class Accordion {
   //
   //--------------------------------------------------------------------------
 
+  connectedCallback(): void {
+    this.passPropsToAccordionItems();
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion/accordion.tsx:86]: maybe call this `updateAccordionItems`?

File: packages/calcite-components/src/components/accordion/accordion.tsx (hunk 1 above)
Comment (driskull) [reply packages/calcite-components/src/components/accordion/accordion.tsx:150]: there's already a var that can be used for the items `this.items` instead of `accordionItems`

**Review by driskull — COMMENTED** [review]
Looking good! Not sure what the issue is. Can you debug and see where the failure is occuring?

File: packages/calcite-components/src/components/accordion-item/accordion-item.tsx (hunk 3 above)
Comment (Elijbet) [reply packages/calcite-components/src/components/accordion-item/accordion-item.tsx:129]: Hmm... not sure how to achieve this. What do you have in mind?

File: packages/calcite-components/src/components/accordion-item/accordion-item.tsx [hunk 6]
```diff
@@ -69,6 +68,36 @@ export class AccordionItem implements ConditionalSlotComponent {
   /** Displays the `iconStart` and/or `iconEnd` as flipped when the element direction is right-to-left (`"rtl"`). */
   @Prop({ reflect: true }) iconFlipRtl: FlipContext;
 
+  /**
+   * Specifies the placement of the icon in the header inherited from the `calcite-accordion`.
+   *
+   * @internal
+   */
+  @Prop({ reflect: false }) iconPosition: Position = "end";
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion-item/accordion-item.tsx:76]: @Elijbet `reflect: false` is the default so I don't think this needs to be specifically defined in the code. Applies to other props.

Comment (driskull) [reply packages/calcite-components/src/components/accordion-item/accordion-item.tsx:76]: For these new internal props, do they need to have a default set or could they be undefined by default?

File: packages/calcite-components/src/components/accordion-item/accordion-item.tsx (hunk 3 above)
Comment (driskull) [reply packages/calcite-components/src/components/accordion-item/accordion-item.tsx:129]: What I was thinking is that the owning accordion could set itself on the items as the parent. Just like how its setting the icontype, iconPosition, scale.

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 7]
```diff
@@ -116,9 +144,17 @@ export class Accordion {
   //  Private State/Props
   //
   //--------------------------------------------------------------------------
+  mutationObserver = createObserver("mutation", () => this.updateAccordionItems());
 
   /** created list of Accordion items */
-  private items = [];
+  accordionItems: HTMLCalciteAccordionItemElement[] = [];
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion/accordion.tsx:150]: Instead of adding `accordionItems` can we just use the existing `this.items`? It just seems like adding a redundant private property.

**Review by driskull — DISMISSED** [review]
Looking good @Elijbet ✨ 👍

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 8]
```diff
@@ -62,13 +81,22 @@ export class Accordion {
   //
   //--------------------------------------------------------------------------
 
+  connectedCallback(): void {
+    this.mutationObserver?.observe(this.el, { childList: true, subtree: true });
```
Comment (jcfranco) [inline packages/calcite-components/src/components/accordion/accordion.tsx:85]: I _think_ `childList` should suffice since we would only update items when the direct children change, and not the children of each item (i.e., nesting is not supported).

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 9]
```diff
@@ -116,9 +144,17 @@ export class Accordion {
   //  Private State/Props
   //
   //--------------------------------------------------------------------------
+  mutationObserver = createObserver("mutation", () => this.updateAccordionItems());
```
Comment (jcfranco) [inline packages/calcite-components/src/components/accordion/accordion.tsx:147]: Please add a newline above this to preserve comment divider spacing.

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 10]
```diff
@@ -82,17 +85,21 @@ export class Accordion {
...
 
   componentDidLoad(): void {
     if (!this.sorted) {
-      this.items = this.sortItems(this.items);
+      this.accordionItems = this.sortItems(this.accordionItems);
       this.sorted = true;
     }
   }
 
+  // componentDidRender(): void {
```
Comment (driskull) [inline packages/calcite-components/src/components/accordion/accordion.tsx:99]: Can you remove this empty comment block?

File: packages/calcite-components/src/components/accordion/accordion.e2e.ts [hunk 11]
```diff
@@ -33,11 +41,26 @@ describe("calcite-accordion", () => {
...
-    expect(element).toEqualAttribute("icon-type", "chevron");
+
+    expect(await element.getProperty("appearance")).toBe("solid");
+    expect(await element.getProperty("iconPosition")).toBe("end");
+    expect(await element.getProperty("scale")).toBe("m");
+    expect(await element.getProperty("selectionMode")).toBe("multiple");
+    expect(await element.getProperty("iconType")).toBe("chevron");
+  });
+
+  it("renders inheritable props: `iconPosition`, `iconType`, `selectionMode`, and `scale` to match those set on parent (non-default)", async () => {
```
Comment (jcfranco) [inline packages/calcite-components/src/components/accordion/accordion.e2e.ts:52]: Could you also add a test to cover #6199?

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 12]
```diff
@@ -117,8 +135,26 @@ export class Accordion {
...
+    for (const mutation of mutationList) {
+      if (mutation.type === "childList") {
+        const addedNodes = Array.from(mutation.addedNodes);
+        addedAccordionItem = addedNodes.find(
+          (node) => node instanceof HTMLCalciteAccordionItemElement
+        ) as HTMLCalciteAccordionItemElement;
+      }
+    }
+    const childNodes = Array.from(this.el.childNodes);
+    const position = childNodes.indexOf(addedAccordionItem);
```
Comment (jcfranco) [inline packages/calcite-components/src/components/accordion/accordion.tsx:149]: Do you still need `position` and sort by it after setting up the mutation observer? I think this could be simplified by updating accordion items by their order in the DOM.

**Comment by jcfranco** [comment]
> This should resolve https://github.com/Esri/calcite-components/issues/6199

This means this PR is a fix and no longer a refactor. 🥳

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 13]
```diff
@@ -132,6 +153,24 @@ export class Accordion {
   //
   //--------------------------------------------------------------------------
 
-  private sortItems = (items: any[]): any[] =>
-    items.sort((a, b) => a.position - b.position).map((a) => a.item);
+  private updateAccordionItems = (addedAccordionItem?: HTMLCalciteAccordionItemElement): void => {
+    if (addedAccordionItem) {
```
Comment (benelan) [inline packages/calcite-components/src/components/accordion/accordion.tsx:157]: What happens if an accordion item is removed from the DOM? Does it get removed from `accordionItems` somehow or will that cause issues?

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 14]
```diff
@@ -132,6 +153,24 @@ export class Accordion {
...
+      this.accordionItems.push(addedAccordionItem);
+    } else {
+      const accordionItemsQueryArray = Array.from(
+        this.el.querySelectorAll("calcite-accordion-item")
+      );
+      this.accordionItems = accordionItemsQueryArray;
```
Comment (benelan) [inline packages/calcite-components/src/components/accordion/accordion.tsx:163]: What is the purpose of pushing `addedAccordionItems` into `accordionItems` if `accordionItems` is being re-referenced to `accordionItemsQueryArray` directly afterwards?

**Review by benelan — COMMENTED** [review]
I have a couple quick questions questions. Also can you change the PR title to be about #6199 rather than the refactor, since the fix is what will show up in the changelog

File: packages/calcite-components/src/components/accordion/accordion.tsx (hunk 13 above)
Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx:157]: Nevermind it looks like it will get removed on line 163, but my question below still stands

Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx:157]: Although it looks like `updateAccordionItems()` exits early if there were no items added. So do we need to handle items being removed separately? I haven't spent a lot of time working in accordion so it's an open question, could be fine as is.

File: packages/calcite-components/src/components/accordion/accordion.tsx (hunk 14 above)
Comment (Elijbet) [reply packages/calcite-components/src/components/accordion/accordion.tsx:163]: Looks like it isn't needed anymore. Removing position removed the need for accordionItems being an array of objects, which makes that bit redundant.

File: packages/calcite-components/src/components/accordion/accordion.tsx [hunk 15]
```diff
@@ -128,18 +128,7 @@ export class Accordion {
...
-    let addedAccordionItem: HTMLCalciteAccordionItemElement;
-    for (const mutation of mutationList) {
-      if (mutation.type === "childList") {
-        const addedNodes = Array.from(mutation.addedNodes);
-        addedAccordionItem = addedNodes.find(
-          (node) => node instanceof HTMLCalciteAccordionItemElement
-        ) as HTMLCalciteAccordionItemElement;
-      }
-    }
-    this.updateAccordionItems(addedAccordionItem);
```
Comment (benelan) [inline packages/calcite-components/src/components/accordion/accordion.tsx]: Hmm idk how I feel about this. Removing this part will have a performance impact because now the DOM is being queried on every mutation, whereas before it was only being queried when nodes were added. 

`querySelectorAll` is a pretty intensive task, especially for something like accordion which can have a yuuge amount of child nodes.

Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx]: Do we really need to query the DOM at all? We should be able to get the added/removed/target nodes from the mutation observer right

Comment (Elijbet) [reply packages/calcite-components/src/components/accordion/accordion.tsx]: updateAccordionItems() runs also on watcher for a number of props that are set by parents on children. We need to keep track of items for updateAccordionItems to map set props/prop changes onto them. Looks like at this point that's all updateAccordionItems is doing, as we no longer keep track of position, or items being added because of the query.

Mutation observer track additions, removals, and attribute changes, right? If that's the case why do we even need a watcher? We could just run the update function to sync props on component load in addition to the observer, but we'd need to query still.

Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx]: Yeah now that the constraint of only querying when the mutation included addedNodes is removed, I'm pretty sure the watchers are redundant. 

However I'm still concerned about using querySelectorAll on every mutation. There has to be a better way to do this that doesn't have the potential to explode someone's computer. Found this explaination after some googling: https://stackoverflow.com/a/39332340

Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx]: Nevermind, it looks like the MutationObserver isn't set up to observe attributes so I think we would still need to watchers

Comment (benelan) [reply packages/calcite-components/src/components/accordion/accordion.tsx]: Also it's not watching the whole subtree so the performance hit won't be too bad, I guess. Does the current logic cover nested accordions or accordion items?

File: packages/calcite-components/src/components/accordion/accordion.e2e.ts [hunk 16]
```diff
@@ -33,11 +41,54 @@ describe("calcite-accordion", () => {
...
+    </calcite-accordion>`);
+    const element = await page.find("calcite-accordion");
+
+    expect(await element.getProperty("iconPosition")).toBe("start");
+    expect(await element.getProperty("iconType")).toBe("plus-minus");
+    expect(await element.getProperty("selectionMode")).toBe("single-persist");
+    expect(await element.getProperty("scale")).toBe("l");
+  });
+
+  it("accordion properties can be set as an attribute as well as a prop", async () => {
```
Comment (jcfranco) [inline packages/calcite-components/src/components/accordion/accordion.e2e.ts:66]: This test would be covered by using the `reflects` test helper.

**Review by jcfranco — APPROVED** [review]
Once the review comments have been addressed, this should be good to merge! 🚀
